### PR TITLE
Various documentation fixes and enable custom partner ID

### LINKED ISSUE #349: Documentation for data.azuread_users is incorrect
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `data.azuread_user` (v1.0.0)

### References

[https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/users](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/users)

### Issue

The title page is incorrect; reads **azuread_user** instead of **azuread_users**

The output from a user block does not contain the **id** attribute. It is instead named **object_id**

image

### PR DESCRIPTION
**Pull request by manicminer**
- Enable a custom partner ID
- Fix some typos
- Bring example configs up to date
- Present example AAD roles as a table
- Document the `metadata_host` provider attribute
- Add provider attributes for configuring partner ID
- Clarify that MSI authentication only works for the current tenant

Closes #349

### CODE REVIEW

File: internal/services/configure_client.go [hunk 1]
```diff
@@ -14,6 +14,8 @@ import (
 	"github.com/terraform-providers/terraform-provider-azuread/version"
 )
 
+const TerraformPartnerID = "222c6c49-1b0a-5959-a213-6608f9eb8820"
```
Comment (katbyte) [inline internal/services/configure_client.go:17]: Does this need to be public?

**Review by katbyte — APPROVED** [review]
LGTM 👍

File: internal/services/configure_client.go (hunk 1 above)
Comment (manicminer) [reply internal/services/configure_client.go]: It does not! :)
