### PR TITLE
azuread_application - support for the `owners` property

### LINKED ISSUE #153: Set owners on azuread_application resources
This is a duplicate of #46 which appears to be closed and implemented, but does not work with the latest release (0.6.0).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
Terraform v0.12.6
+ provider.azuread v0.6.0
```

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "test" {
  name                       = "app-owner-test"
  owners                      = "${var.app_owner}"
  available_to_other_tenants = false
}
```

### Expected Behavior

Assign owners to the application registration in Azure.

### Actual Behavior

```
Error: Unsupported argument

  on main.tf line 10, in resource "azuread_application" "test":
  10:   owners                      = "${var.app_owner}"

An argument named "owners" is not expected here.
```

### Steps to Reproduce

1. `terraform plan`

### References

* #46

### PR DESCRIPTION
**Pull request by katbyte**
fixes #153

### CODE REVIEW

File: azuread/data_application_test.go [hunk 1]
```diff
@@ -4,36 +4,37 @@ import (
...
 			},
 			{
-				Config: testAccAzureADApplicationDataSource_objectId(id),
+				Config: testAccAzureADApplicationDataSource_objectId(ri),
 				Check: resource.ComposeTestCheckFunc(
 					testCheckADApplicationExists(dataSourceName),
-					resource.TestCheckResourceAttr(dataSourceName, "name", fmt.Sprintf("acctestApp-%s", id)),
-					resource.TestCheckResourceAttr(dataSourceName, "homepage", fmt.Sprintf("https://acctestApp-%s", id)),
+					resource.TestCheckResourceAttr(dataSourceName, "name", fmt.Sprintf("acctest-APP-%d", ri)),
+					resource.TestCheckResourceAttr(dataSourceName, "homepage", fmt.Sprintf("https://acctest-APP-%d", ri)),
```
Comment (tracypholmes) [inline azuread/data_application_test.go]: There shouldn't be an issue with `acctestApp` vs `acctest-APP`correct?
